FROM apache/airflow:3.0.0

#create models directory and set ownership
USER root
RUN mkdir -p /app/models

USER airflow
#Copy requirements file
COPY requirements.txt /tmp/requirements.txt

#install python packages as root (system-wide)
RUN pip install -r /tmp/requirements.txt 

#switch back to airflow user for safety
USER airflow 